---
name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.7]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - name: Test
      run: make test
