---
name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.7]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - name: Test
      run: make test
