name: verify

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.17.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version:  ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1 # v3.1.0
        timeout-minutes: 5
        with:
          version: v1.44.2
      - run: |
          go mod tidy
          git diff --exit-code
